### ISSUE TITLE
Idea: Generalized workflow for fetching the different data sources

### ISSUE THREAD

**Issue by TK5-Tim** [PySport/kloppy#1]
My idea is a workflow of fetching data from different data sources without having to code the whole import all the time. 

The goal would be to have a Framework that includes maximal possible implementation for a generalized data import. So that you have less work if you want to add different sources. 
You probably cannot would not have a "one implementation fits all" solution because the way data is available always is a little bit different. 

My idea is inspired by the AutoPKG Projekt (https://github.com/autopkg/autopkg). 
The idea is to have a basic structure of how to input the data. 
By using different processors for different types of data and the specific arguments for an API or for the website where the data is stored. By passing Arguments to the Processors all the details can be set. 
It would be something where you can start by having only one or two different possibilities and then add over time. 

So in the end you would need: 
- The basic Framework for fetching the data 
- The Processors and the Arguments for the different types how the data is available

By writing this down I see this idea has still a lot of holes to fill. So if it is unclear or just not realistic, just close the issue. 
The project you started is really inspiring and I hope I can contribute in some sort of way. 
Have a nice evening!

**Comment by koenvo** [comment]
I think what you are describing makes sense. It would help a lot when there are a datasource/fetcher with a standard interface available for all kind of sources. The implementation of such an DataSource doesn't need to be known by the user, only the arguments it need.

For now I only have the details for how to fetch the data for StatsBomb event data. Not sure if other providers have a API available for programmatic retrieval. Need to figure that out

**Comment by koenvo** [comment]
Hi Tim,

I partly implemented your proposal. Because I don’t know all the apis of the providers yet, I implemented a way to load public available datasets. 

First one is Metrics tracking data but others should follow shortly.

Can you have a look at https://github.com/PySport/kloppy/blob/master/examples/datasets/metrica.py and let me know if this helps you?

**Comment by TK5-Tim** [comment]
That looks great! Thank you very much. Very cool what are you building up with kloppy :)
