### ISSUE TITLE
Restructure documentation

### ISSUE THREAD

**Issue by koenvo** [PySport/kloppy#117]
Current documentation located at https://kloppy.pysport.org contains same-like content at different places, and also problems are solved in different ways. The documentation should be super easy.

Structure should be:

- Home _(very short intro like https://github.com/PySport/kloppy/blob/master/README.md#what-is-it)_
- Getting-started _(Notebook files containing best practices for loading data for **all** providers)_
  - Opta
  - Metrica
  - etc
  - Open data   
- Examples _(All kind of examples for common tasks, like transforming stuff etc)_
- API Reference
- Providers
- Other
  - Issues
  - Contributing
  - License
  - About
  - Changelog

**Comment by bdagnino** [comment]
@koenvo Looks good to me!
