### ISSUE TITLE
Add freeze frame to event data

### ISSUE THREAD

**Issue by koenvo** [PySport/kloppy#122]
Include the `freeze_frame` of Statsbomb 360 data.

This opens up the ability to use tracking data to add a freeze frame to event data. This does not include changes to to_pandas. Users can extract useful features use a `record_converter`

See also https://github.com/PySport/kloppy/pull/64

Statsbomb data: https://github.com/statsbomb/open-data/blob/master/doc/Open%20Data%20360%20Frames%20v1.0.0.pdf

**Comment by probberechts** [comment]
This was added in https://github.com/PySport/kloppy/pull/164.
