### ISSUE TITLE
Add Formation State to Opta Deserializer

### ISSUE THREAD

**Issue by MKlaasman** [PySport/kloppy#124]
Currently Kloppy enables to add multiple states, "score", "lineup", "sequence", to the dataset using the add_state() method (see: https://kloppy.pysport.org/api/domain/event/#kloppy.domain.models.event.EventDataset.add_state). I would propose adding a "formation" state to this list.

It would be beneficial if this state_builder would feature the possibility of adding the formation of both teams. Comparable with the Score state, this will give the user the opportunity to add columns: "home_formation" and "away_formation" columns to his/her DataFrame. Making filtering of events based on formation possible. Opta makes use of a qualifier_id that corresponds with a formation as shown below:

formation_names = {
    2: "4-4-2",
    3: "4-1-2-1-2",
    4: "4-3-3",
    5: "4-5-1",
    6: "4-4-1-1",
    7: "4-1-4-1",
    8: "4-2-3-1",
    9: "4-3-2-1",
    10: "5-3-2",
    11: "5-4-1",
    12: "3-5-2",
    13: "3-4-3",
    14: "3-1-3-1-2",
    15: "4-2-2-2",
    16: "3-5-1-1",
    17: "3-4-2-1",
    18: "3-4-1-2",
    19: "3-1-4-2",
    20: "3-1-2-1-3",
    21: "4-1-3-2",
    22: "4-2-4-0",
    23: "4-3-1-2",
    24: "3-2-4-1",
    25: "3-3-3-1",
}

I am currently working on an implementation, however, I am curious whether people have some remarks.

**Comment by koenvo** [comment]
This sounds super useful! Can you elaborate a bit on how opta specifies this information? Is it a qualifier on each event or are there “formation changed” events?

For later: it would be nice if those events can be generated based on tracking data when event data provider doesn’t include them.

**Comment by MKlaasman** [comment]
The F24 (events file) contain the following associated information:
Both event type_id “34” and “40” consist of a qualifier_id “130” (Team formation. Type_id “34” is an event consisting of the team set up and are normally the first and second event of an opta F24 file (one event for each team). 
When an event has a type_id of “40”, it specifies a formation change. Meaning that the team alters its formation. 
In both cases qualifier_id=”130” specifies the team’s formation given an identifier, between 2 and 25 as seen in the list above (previous comment).

Moreover, the F7 file consist of a Formation element in the TeamData. However, it looks like this formation is not always consistent with the set-up formation (type_id 34). For this reason, I am not certain whether to pick the information from the F7 file or the F24 file as the starting formation. 

@koenvo So to answer your question Koen, it is specified by a qualifier_id, namely "130" and there are also "formation changed" events. It could be sufficient to only look at the qualifier_id "130".

![event_id_information](https://user-images.githubusercontent.com/59951106/147911823-8cf88a3e-881a-4d3c-8952-36657d612002.png)

**Comment by MKlaasman** [comment]
After asking a few people and diving a little bit deeper into multiple F-files, I came to the conclusion that the "Starting Formation" from the F7 files and the event type_id="34" will consist of the same formation.

**Comment by koenvo** [comment]
Thanks for your contribution @MKlaasman !
