### ISSUE TITLE
Bug in orientation transformation

### ISSUE THREAD

**Issue by probberechts** [PySport/kloppy#134]
The orientation transform does not work correctly for events in which the ball-possessing and action-executing teams differ. As an illustration, consider the example below.
 
```py
from kloppy import statsbomb

# load data of the 2018 FIFA World Cup Final
dataset = statsbomb.load_open_data(match_id=8658)
```

This dataset has an "action-executing-team" orientation and the first few actions of the game look like this:

![image](https://user-images.githubusercontent.com/2175271/158847283-2b57fc21-ea20-4b56-ba20-e2404d2d6633.png)

This looks fine. Croatia has possession in the entire sequence. France only touches the ball unsuccessfully in an aerial duel (action nr 10). For reference, you can find the video here: https://www.youtube.com/watch?v=7Fau-IwbuJc

```
# convert orientation
transfomed_dataset = dataset.transform(
    to_orientation=Orientation.FIXED_HOME_AWAY,
)
```

When transforming to a "fixed-home-away" orientation, I obtain the following result.

![image](https://user-images.githubusercontent.com/2175271/158846871-4434af83-410d-496b-a374-93d331ce0345.png)

Action nr 10 should have been flipped.

I do not fully understand the code yet, but maybe it is sufficient to add the ` action_executing_team` parameter [here](https://github.com/PySport/kloppy/blob/015dc38d674213017c0253e0bbaf920c880a3251/kloppy/domain/services/transformers/__init__.py#L273).

**Comment by probberechts** [comment]
Yes, it is indeed event "d6184de7-e045-41f1-acc2-4ada854e90fb" and adding `action_executing_team=event.team` solves it. I don't think it has to be `event.player.team`.

It's more convenient if you quickly make this one-line change and verify that it does not break anything else. You might have to apply the same fix to the tracking data logic.

**Comment by koenvo** [comment]
Would you mind checking https://github.com/PySport/kloppy/pull/139 ?

**Comment by probberechts** [comment]
Looks good to me. Thanks for the quick fix!

**Comment by koenvo** [comment]
Thanks for checking! 

Issue fixed in https://github.com/PySport/kloppy/pull/139
