### ISSUE TITLE
Add a data model for duels

### ISSUE THREAD

**Issue by probberechts** [PySport/kloppy#135]
Kloppy's event data model currently does not support events that can be categorized as duels such as tackles, 50/50s, aerials, ...

### How data providers do it

**StatsBomb** has "50/50" and "Duel" (with types "Aerial Lost" and "Tackle") events. Aerials that are won are included in a "Shot", "Clearance", or "Miscontrol" event.

 **Opta** has "50/50", "aerial" and "tackle" events

 **Wyscout**  has a "Duel" event with subtypes "Sliding Tackle", "Offensive duel", "Defensive duel", "Loose ball duel", and "Aerial duel".

**SoccerAction** has a "tackle" action for ground duels. Aerial duels are ignored.

### Proposal

Add a `DuelEvent` to Kloppy with qualifiers "Aerial", "Ground", "Sliding Tackle" and "LooseBall".

**Comment by MKlaasman** [comment]
@probberechts 
In this proposal, should StatsBomb and Opta “tackle” Event (/type) be qualified as a “Ground” or a “Sliding Tackle”? 

I would expect "Tackle" & "Sliding Tackle" to be different. SoccerAction only has a "tackle" action. So, if we want to be able to get all tackles as discussed in: https://github.com/ML-KULeuven/socceraction/pull/229 , then tackles should not be part of the "Ground" qualifier. 

Proposal
We could change the "Sliding Tackle" to "Tackle" which would include the WyScout "Sliding Tackle" and all other providers Tackle events. 

What do you think?

**Comment by probberechts** [comment]
My initial idea was to give all non-aerial duels the `Ground` qualifier. For Wyscout, a "Sliding Tackle" would get both the `Ground` and `Sliding Tackle` qualifiers. Similarly, StatsBomb's 50/50 events would get both the `LooseBall` and `Ground` or `Aeria`" qualifiers. As such, you keep all information available from the original data streams.

In socceraction, a "tackle" action would map to a kloppy `DuelEvent` with the `Ground` qualifier and no `LooseBall` qualifier.

I guess it could be useful in some analysis to distinguish between standing and sliding tackles, as sliding tackles are typically higher risk. But personally, I don't care that much.

**Comment by koenvo** [comment]
Solved in https://github.com/PySport/kloppy/pull/204
