### ISSUE TITLE
Add a data model for bad touches

### ISSUE THREAD

**Issue by probberechts** [PySport/kloppy#136]
Kloppy's event data model currently does not support bad touches / miscontrols, which are events in which a player loses the ball due to a bad touch.

### How data providers do it

**StatsBomb** has a "miscontrol" event.

 **Opta** has a "ball touch" event with outcome 1 if the ball simply hit the player unintentionally and outcome 0 if the player unsuccessfully controlled the ball.

 **Wyscout**  has a "touch" event with attribute "missed" or "dummy" when the player doesn't touch ball on purpose.

**SoccerAction** has a "bad touch" action.

### Proposal

Either add a `MisControlEvent` or a `BallTouchEvent` with qualifiers to distinguish between a miscontrol and dummy touch to Kloppy. However, I do not think the "dummy touch" adds a lot of value and is not supported by all providers, so I think it would be fine to omit this from Kloppy's model.

**Comment by joemulberry** [comment]
Is there an agree preference for either MisControlEvent or BallTouchEvent?

**Comment by MKlaasman** [comment]
I agree with @probberechts statement, that the "dummy touch" adds no value. Therefore I propose adding solely a MisControlEvent. 

If @koenvo & @JanVanHaaren agree, I can start on this issue.
