### ISSUE TITLE
Add a data model for clearances

### ISSUE THREAD

**Issue by probberechts** [PySport/kloppy#137]
Kloppy's event data model currently does not support clearances. These are commonly defined as "an action by a defending player to clear the danger without an intention to deliver it to a teammate".

### How data providers do it

**StatsBomb** , **Opta** , **Wyscout**  and **SoccerAction** all have a custom event for clearances. This is a very simple event without outcome or custom subtypes.

### Proposal

Add a `ClearanceEvent` to Kloppy.

**Comment by koenvo** [comment]
Solved in https://github.com/PySport/kloppy/pull/195
