### ISSUE TITLE
Add a data model for keeper actions

### ISSUE THREAD

**Issue by probberechts** [PySport/kloppy#138]
Kloppy's event data model currently does not support keeper actions. It would be great if this could be added.

### How data providers do it

**StatsBomb** has a single "Goal Keeper" event where the type of the intervention is coded as "Collected", "Goal Conceded", "Keeper Sweeper", "Penalty Conceded", "Penalty Saved", "Punch", "Penalty Saved To Post", "Save", "Saved to Post", "Shot Faced", "Shot Saved", "Shot Saved Off T", "Shot Saved To Post" and "Smother".

**Opta** has seven keeper events: "Save", "Claim", "Punch", "Cross not claimed", "Smother", "Keeper pick-up", and "Penalty faced".

**Wyscout** has "Shot against (Save attempt)" and "Goalkeeper leaving line" events.

**SoccerAction** maps keeper events to four actions: "keeper_save", "keeper_claim", "keeper_punch" and "keeper_pick_up".

### Proposal

I suggest creating a single `GoalkeeperEvent` and use `GoalkeeperQualifiers` to distinguish between a `Save`, `Claim`, `Punch`, `PickUp` and `Smother`.

**Comment by joemulberry** [comment]
Is this widely accepted as an agreed plan?

**Comment by MKlaasman** [comment]
@koenvo & @JanVanHaaren do you see any caveats in this proposal?

If not, then I can start on this issue.

**Comment by koenvo** [comment]
Fixed in https://github.com/PySport/kloppy/pull/196
