### ISSUE TITLE
End coordinates missing for offside passes (Opta)

### ISSUE THREAD

**Issue by MKlaasman** [PySport/kloppy#155]
Not sure whether it is a design choice to not include end coordinates for offside passes. 

However, I suppose there are use-cases for wanting to investigate the direction & end location of an offside pass.
IMO the positives outweigh the negatives in terms of adding the end_coordinates in this use-case.

Background info:
Within the Opta data, offside passes have a different type_id (type_id == 2) compared to normal passes (type_id == 1).
Offside is thus not a subtype/qualifier of the main event pass. For this reason, they are handled differently by Kloppy:
- _parse_pass()
- _parse_offside_pass()

To do:
- add receiver_coordinates to _parse_offside_pass()

Not sure whether the same "issue" is present for other providers.

**Comment by koenvo** [comment]
Thanks for solving this issue!
