### ISSUE TITLE
Support Wyscout event data v3

### ISSUE THREAD

**Issue by DriesDeprest** [PySport/kloppy#169]
Kloppy currently only supports loading Wyscout v2 event data, while Wyscout v3 event data is the new standard. It would be great to add support for loading Wyscout v3 data.

![image](https://user-images.githubusercontent.com/46134788/218786128-770f900b-8fc1-4b42-9c5a-e72537d5dbf8.png)

**Comment by JanVanHaaren** [comment]
Yes, I agree that adding support for the V3 specification of the Wyscout event data would be great.

**Comment by koenvo** [comment]
Fixed in https://github.com/PySport/kloppy/pull/170. Thanks a lot!
