### ISSUE TITLE
Incorrect home/away mapping in Statsbomb metadata

### ISSUE THREAD

**Issue by KubaMichalczyk** [PySport/kloppy#171]
When working with Statsbomb data I've noticed that the home and away teams are not always parsed correctly. This is probably because they are loaded from lineup data.

https://github.com/PySport/kloppy/blob/abd9af208bbf0505731bc9ef21a9778c5a8317e9/kloppy/infra/serializers/event/statsbomb/deserializer.py#L508

The match files provided by Statsbomb with detailed match metadata should probably be used instead. Here are some examples of discrepancies (in my little experience this happens about every second case):

![image](https://user-images.githubusercontent.com/37018819/219855346-8119906b-e4d3-49fd-8fc0-2b1afff5f4fb.png)

```
import requests
from kloppy import statsbomb
from kloppy.domain.models import Ground

response = requests.get("https://raw.githubusercontent.com/statsbomb/open-data/master/data/matches/11/1.json")
matches = response.json()

count = 0
for match in matches:
    dataset = statsbomb.load_open_data(str(match['match_id']))
    parsed_home_team = [team.team_id for team in dataset.metadata.teams if team.ground == Ground.HOME][0]
    if str(match['home_team']['home_team_id']) != str(parsed_home_team):
        print("Match ID: ", match['match_id'])    
        print("home team from matches file: ", match['home_team']['home_team_id'])
        print("home team stated in metadata: ", parsed_home_team)
        print('\n')
        count += 1
```

**Comment by koenvo** [comment]
Thanks for this bug report!

This is a very interesting issue your are describing here. One slight challenge with your proposed solution is that there is no easy way to go from match_id to match_data. We would need to fetch all matches details first (once, and cache it?) and then find it within all competitions.

The main problem here is that data itself is incorrect. Let me check with Statsbomb if they are able to fix it. Otherwise there needs to be a fix for this in kloppy.

**Comment by KubaMichalczyk** [comment]
Sure, I've added the code below the screenshot.

**Comment by koenvo** [comment]
Thanks. I've checked with match_id=9912 and the error is indeed here:

https://github.com/PySport/kloppy/blob/abd9af208bbf0505731bc9ef21a9778c5a8317e9/kloppy/infra/serializers/event/statsbomb/deserializer.py#L508

It seems the first 'Starting XI' event indicated the home team. Ran code below and all matched.

```python
import requests
from kloppy import statsbomb

response = requests.get("https://raw.githubusercontent.com/statsbomb/open-data/master/data/matches/11/1.json")
matches = response.json()

count = 0
for match in matches:
    dataset = statsbomb.load_open_data(str(match['match_id']))

    # This is the first 'Starting XI' event
    parsed_home_team = dataset.events[0].team.team_id
    if str(match['home_team']['home_team_id']) != str(parsed_home_team):
        print("Match ID: ", match['match_id'])
        print("home team from matches file: ", match['home_team']['home_team_id'])
        print("home team stated in metadata: ", parsed_home_team)
        print('\n')
        count += 1
```

Let me double check with Statsbomb if this assumption is correct.

**Comment by koenvo** [comment]
Confirmed by SB. Let me create a fix for this
