### ISSUE TITLE
Support StatsPerform Tracking data

### ISSUE THREAD

**Issue by MKlaasman** [PySport/kloppy#184]
**Description**
There is no implementation for loading StatsPerform tracking data. To allow Kloppy to load this data, there should be added an extra deserializer for StatsPerform. 

**Proposal**

- Create _serializers/tracking/statsperform.py_ : that handles the loading of StatsPerform tracking data with input files being: metadata.xml, players.csv & tracking.txt
- Add _test_statsperform.py_
- Add StatsPerform coordinate system to _common.py_  (x: 0,100 & y: 0,100)

**Comment by JanVanHaaren** [comment]
Hi Milan. I like the idea of adding a deserializer for Stats Perform!

1. I believe that Stats Perform are currently using slightly different setups in different leagues. Do I understand correctly that your proposal refers to SportVU 2.0? If so, I would be in favor of being more explicit about it.
2. I am a bit confused regarding the three required input files. Based on the pull request, the `metadata.xml` file appears to contain the MA25 feed from the Stats Perform API, whereas the `players.csv` and `tracking.txt` files appear to be in the Stats format. Is there a chance that we could rely entirely on responses from the Stats Perform API? For example, take the metadata from the MA1 feed and the tracking data from the MA25 feed?

**Comment by denizcanoruc** [comment]
Hi Milan @MKlaasman and Jan @JanVanHaaren ,

I have already implemented both tracking and event data serializer for StatsPerform for a project of mine. But it has some minor bugs right now I need to fix. If it fits you, I can share it with you after fixing the bugs. It can take about 2 days.

**Comment by MKlaasman** [comment]
@denizcanoruc Requirements here are that it fits in the Kloppy structure. 

If you think it can be beneficial for the implementation, you can always reach-out to me via LinkedIn or Twitter.

**Comment by JanVanHaaren** [comment]
While reviewing pull request #191, I was wondering the following: What would be the best way to deal with data providers that provide their data in multiple formats? For example, the Stats Perform API supports both XML and JSON, but the current implementation of the deserializer only supports XML. Should we make this more explicit by, for example, including XML in the name of the deserializer class? Any thoughts, @koenvo?

**Comment by koenvo** [comment]
### Be explicit

Being explicit and have 'xml' or something in the class name (and corresponding function in `kloppy/<vendor>.py`) makes sense. People will often know in what format they have the files. And especially when `kloppy` is used within a bigger python program, the program should know the format upfront.

### or Auto-detect

In the future it might be nice to auto detect the format of the files and determine how to deserialize it.


### or Split deserialize and parse
Currently we call it deserializers but they also do the parsing. We *could* split it.

Is the data exactly the same but only in a different format? In that case we could - also in the future - make a split between reading/deserialize the files into a `dict` and parsing into kloppy objects. Like this:

<img width="1024" alt="image" src="https://github.com/PySport/kloppy/assets/3765024/d15d2139-5690-4cf4-aa5f-c119e9123354">

**Comment by JanVanHaaren** [comment]
Yes, the data is exacty the same but the delivery format is different.

I would be in favor of separating the deserialization and parsing functionality in the future. Besides simplifying the deserializers, this separation would also be helpful for users who would want to store the raw data in an alternative way. They would only need to implement a custom deserializer and could re-use the parser.

I also think that both the second and the third option could be implemented. We could still have a single entry point for a data provider and then automatically detect the appropriate deserializer from the data.

**Comment by JanVanHaaren** [comment]
Issue addressed by pull request https://github.com/PySport/kloppy/pull/191.
