### ISSUE TITLE
Wyscout event data serializer

### ISSUE THREAD

**Issue by koenvo** [PySport/kloppy#22]

**Comment by schmidtfx** [comment]
Any status on this one?

**Comment by koenvo** [comment]
Not yet. If you have documentation on the format we can have a look at it. So far no people asked for it nor did we have docs on the format

**Comment by schmidtfx** [comment]
I have started to WyScout integration: https://github.com/PySport/kloppy/pull/79
This is very early stage code and not yet complete.

**Comment by schmidtfx** [comment]
@koenvo can you link this issue with the pull request #79 ?
