### ISSUE TITLE
[StatsBomb] How to deserialize Collected and KeeperSweeper events

### ISSUE THREAD

**Issue by probberechts** [PySport/kloppy#225]
The StatsBomb deserializer does not yet implement the following goalkeeper action types:
- `CLAIM`: Goalkeeper catches cross.
- `PICK_UP`: Goalkeeper picks up ball.

I wanted to add these in #224, but realized that a few things are unclear to me and have to be resolved first.

1. I assume these correspond to the  StatsBomb 25/"Collected" and 27/"KeeperSweeper"  (with outcome  47/"Claim") events. Yet, it is unclear what the difference is between both event types. Does anyone know?
2. I assume that you'll have to look at the previous action to infer whether the "Collected" or "KeeperSweeper" event should be converted to a `CLAIM` or `PICK_UP`.
3. There are three other outcomes of the "KeeperSweeper" event which do not seem to have a counterpart in Kloppy.
    - 4/"Won": Retained possession
    - 15/"Success": Keeper sweeper action where keeper collects the ball
    - 48/"Clear": Keeper sweeper action where keeper clears the ball
   
    Should we introduce another goalkeeper action type, or do we convert these to a `PASS` , `CLEARANCE` or something else?

**Comment by JanVanHaaren** [comment]
Regarding your first question, I believe that "Collected" is used when a goalkeeper catches a ball that is crossed towards the goalkeeper area (e.g., a corner kick or an open-play cross) and that "Keeper Sweeper" is used when a goalkeeper comes off his line to contest the ball (e.g., a goalkeeper coming off his line to either catch or clear the ball).

**Collected**
![Cross](https://github.com/PySport/kloppy/assets/5039319/c7ba4c95-02c7-4dfa-9ea2-e943a6924bc8)
![Collected](https://github.com/PySport/kloppy/assets/5039319/c280fd99-dc0f-4884-a470-34fa0243763f)

**Keeper Sweeper - Claim**
![Keeper Sweeper](https://github.com/PySport/kloppy/assets/5039319/aba5bda3-deac-42bc-b60f-df35c1074b3f)
![Claim](https://github.com/PySport/kloppy/assets/5039319/7c0bec21-9855-470a-8b91-8fa13f7e0cb8)

**Comment by probberechts** [comment]
Great, because that would mean that we can use the following mapping:

- type="Collected" --> `GoalKeeperActionType.CLAIM`
- type="KeeperSweeper" + outcome="Claim" --> `GoalKeeperActionType.PICK_UP`

This already solves my first two questions.
