### ISSUE TITLE
Incorrect Wyscout v2 test data?

### ISSUE THREAD

**Issue by probberechts** [PySport/kloppy#234]
The structure of the list of player and team objects in the [test files](https://github.com/PySport/kloppy/blob/master/kloppy/tests/files/wyscout_events_v2.json) differs from what is defined in the [API docs](https://apidocs.wyscout.com/#tag/Advanced-Stats/paths/~1teams~1%7BwyId%7D~1matches~1%7BmatchWyId%7D~1advancedstats/get) of the Wyscout v2 API.

Specifically, there is an additional level in the official API docs:

```json
"teams": {
    "3166": {
        "team": { <-- this is not in the test file
            "area": {},
            "category": "default",
            "children": [],
            "city": "Bologna",
            "gender": "male",
            "gsmId": 1249,
            "name": "Bologna",
            "officialName": "Bologna FC 1909",
            "type": "club",
            "wyId": 3166
        }
   }
}
```

I don't have access to the API, so it could also be that the docs are incorrect.

**Comment by JanVanHaaren** [comment]
Good catch. I don't have access to the Wyscout V2 match events endpoint either, but the response of the V2 match formations endpoint has an additional `team` level so this might well be a mistake in the test file.
