### ISSUE TITLE
The SkillCorner tracking data deserializer expects a .json file but raw data is in .jsonl format

### ISSUE THREAD

**Issue by DriesDeprest** [PySport/kloppy#251]
The SkillCorner tracking data deserializer expects a .json file, see: https://github.com/PySport/kloppy/blob/master/kloppy/infra/serializers/tracking/skillcorner.py#L254.
While the raw input SkillCorner files received from the API are in .jsonl format: https://skillcorner.com/api/docs#/match/match_tracking_list.

Is this the result of SkillCorner having updated the format in which they share tracking data?

**Comment by JanVanHaaren** [comment]
I believe that SkillCorner changed their output format at some point. I haven't checked, but the current implementation should be compatible with the [SkillCorner Open Data](https://github.com/SkillCorner/opendata) format. Pull request #215 is related.
