### ISSUE TITLE
Inconsistency in the player ID's used between different tracking data deserializers

### ISSUE THREAD

**Issue by DriesDeprest** [PySport/kloppy#254]
In our different tracking data deserializers, we are using different approaches to define the ID's of players. Below an overview of some providers to clarify the differences:

- [SkillCorner](https://github.com/PySport/kloppy/blob/master/kloppy/infra/serializers/tracking/skillcorner.py#L317) : we set player ID as {ground}_{jersey_no}
- [SecondSpectrum](https://github.com/PySport/kloppy/blob/master/kloppy/infra/serializers/tracking/secondspectrum.py#L215) : we set player ID as the Opta ID. 
- [Tracab](https://github.com/PySport/kloppy/blob/master/kloppy/infra/serializers/tracking/tracab.py#L76) : we set player ID as {ground}_{jersey_no}.

Is this behaviour intentional or the result of a not agreed upon standard?

I would have expected the provider ID's would be used where possible. Thus, that e.g. in the case of SkillCorner, we would use the SkillCorner player ID.

**Comment by DriesDeprest** [comment]
@koenvo any thoughts on this? I would like to work on a fix (but first make sure, you are aligned) to integrate it in my project.

**Comment by koenvo** [comment]
Agree on that provider ID should be used where possible.

What do you think @JanVanHaaren ?

**Comment by JanVanHaaren** [comment]
I agree. I would also expect that the data providers' identifiers are used. This approach would also improve the interoperability between `kloppy` and other systems and tools that typically use the data providers' identifiers.

**Comment by DriesDeprest** [comment]
Fixed with https://github.com/PySport/kloppy/pull/278
