### ISSUE TITLE
User Documentation in Github Wiki

### ISSUE THREAD

**Issue by TK5-Tim** [PySport/kloppy#27]
I think it would be very useful to have a full documentation with examples and everything in the github Wiki.
With more and more things being added the ReadMe gets to overcrowded. With the Wiki you can make an extra tab for every topic and can have several or more specific examples. 

Would be happy to help with that!

**Comment by koenvo** [comment]
Do you think the github wiki is better than the solution proposed in https://github.com/PySport/kloppy/issues/6 ?

And totally agree the readme is getting overcrowded!

**Comment by TK5-Tim** [comment]
No #6 looked fine and there should not be much of a difference in useability. I just did not see the issue.
