### ISSUE TITLE
Store the position of a player at moment of event execution and not only starting position

### ISSUE THREAD

**Issue by DriesDeprest** [PySport/kloppy#277]
**Current**
Currently, we only store the starting position of a player in our `EventDataset.metadata.teams[x].players[x].position`. It is also this starting position of the player that we add to every event `EventDataset.events[x].player.position`. 

**Goal**
I believe it would be more accurate to store the position of the player at the time of execution in every event `EventDataset.events[x].player.position`, instead of the starting position.

**Implementation**
For some providers (e.g. Wyscout & StatsBomb) we can derive the position of the player at the moment of the event directly from the raw data.
While for others (e.g. Opta) we would have to derive the position of the players from the starting positions and formation change events in the serializer. In this case, we would update the positions of the different players throughout serializing the raw file so we can use the correct position for each player throughout serialization.

**Comment by JanVanHaaren** [comment]
It would indeed be valuable to keep track of the actual positions of the players throughout a match. In the StatsBomb deserializer, we currently use the _Tactical Shift_ events only to update the teams' formations but we could also use them to update the players' positions.

**Comment by DriesDeprest** [comment]
I was originally planning to not make use of the _Tactical Shift_ events for StatsBomb, but just use the "position" property of each event in the raw data, to set the right position for the player for every event.

This would look something like this:
``` python
player = team.get_player_by_id(raw_event["player"]["id"] if "player" in raw_event else None
if player:
  player.position = Position(position_id=raw_event["position"]["id"], name=raw_event["position"]["name"])
generic_event_kwargs = {..., "player": player, ...}
```
For Wyscout, a similar approach could be used. To make this work, however, we would need to remove the `(frozen=True)` argument from the `@dataclass` decorator wrapping the `Player` class ([context](https://github.com/PySport/kloppy/blob/master/kloppy/domain/models/common.py#L116-L142)). Do you see any problems with that? 

Only for Opta, we would have to derive the position of the players from the starting positions and formation change events in the serializer, as the position of the player is not present in the raw data.

**Comment by probberechts** [comment]
@JanVanHaaren 
>  In the StatsBomb deserializer, we currently use the Tactical Shift events only to update the teams' formations

To be precise, we do not update the `Team`. Instead, we create a `FormationChangeEvent` with a `formation_type` field. From this, we can derive the team's formation in each event using the `FormationStateBuilder`.

@DriesDeprest 
I don't think your approach will work. There is only a single `Player` object for each player and that object is linked with each event. You could create a copy, but I'm not a fan of that. It is convenient to have a single version of each player.

I would either add a list with all positions to the `Player` class. In pseudocode, something like this:

```python
class Player:
   positions: list # [{"from": 0.00 , "to": 234.23, "position": Position("LB")}, ...]
   
   @property
   def starting_position(self):
       return positions[0]
       
   def position(timestamp):
      return next(p for p in positions if p['from'] >= timestamp and p['to'] < timestamp)
```

Or add position changes to the `FormationChangeEvent` / a new event type.

(or both :wink: )

**Comment by DriesDeprest** [comment]
Thanks for sharing @probberechts. Thinking it through, creating a copy of the `Player` object every time a position changes does indeed not feel like a good solution.

I think going from `position` to `positions` for the `Player`class is a good idea.

I'm a bit struggling, however, on how we can neatly implement it. The problem I see is that only at the end of our iteration through all raw events, we have determined for all players what their different positions were throughout the game. Thus, we can only construct the `Player` objects at the end of the raw event deserialization iteration process. While we already need the `Player`objects to pass as arguments to the `Event` objects we are constructing during the deserialization. How would you go about that?

**Comment by JanVanHaaren** [comment]
@DriesDeprest 

You don't need to delay the construction of the `Player` object and also don't need to remove the `frozen` flag from the class. The `frozen` flag only emulates immutability by _disabling_ the assignment and deletion of attributes and raising an error instead.

```python
from dataclasses import dataclass, field

@dataclass(frozen=True)
class Player:
    player_id: str
    positions: list[str] = field(default_factory=list)


player = Player(player_id=13)

player.positions.append('Center Forward')
player.positions
>> ['Center Forward']

player.player_id = 14  # raises FrozenInstanceError: cannot assign to field 'player_id'
```

**Comment by DriesDeprest** [comment]
Got it, thanks for helping me improve my knowledge on this topic! :wink:

Would you then recommend as an implementation to adjust the `positions`attributes of the `Player` objects while iterating through the raw events when recognizing positional changes of players?

For Opta, we would recognize the formation change events and for StatsBomb & Wyscout, we would recognize changes in the `position` property in the raw events for players.

**Comment by probberechts** [comment]
For StatsBomb you can get it efficiently from the lineups.json file.

**Comment by DriesDeprest** [comment]
@probberechts @JanVanHaaren I've started working on this PR: https://github.com/probberechts/kloppy/pull/1. The PR is based from https://github.com/probberechts/kloppy/tree/fix/timestamps, as this branch contains required changes to properly get the current position of player given a period and timestamp.

Looking forward to feedback from @probberechts and @JanVanHaaren before proceeding further with the implementation.

**Comment by probberechts** [comment]
I haven't looked at the code in detail but two high-level remarks that I have are:
1. I would not combine the period id and timestamp in a `TimePoint` object. In itself, it might not be a bad but it does not seem a good idea to do this in this part of the code **only**.
2. It does not seem necessary to store the end timestamp of a position since this is implied by the start timestamp of the next position. I would use an on-change representation here and optionally add a derived property to get the end timestamp.

**Comment by DriesDeprest** [comment]
Thanks for the feedback, it does indeed already look simpler this way. I've implemented the listed changes, let me know if you have additional feedback.

**Comment by koenvo** [comment]
Fixed in https://github.com/PySport/kloppy/pull/326
