### ISSUE TITLE
Metadata model

### ISSUE THREAD

**Issue by bdagnino** [PySport/kloppy#3]
Would be useful to have a game model with pre defined fields that get filled automatically if the data is available on the data package, or could get filled in manually. 

Could be based on the fields/inputs present in the FIFA EPTS standard format:
1. Global
2. Teams 
3. Players

This way independently of the data provider you could have the same fields and know whether they are available or not.

**Comment by koenvo** [comment]
While playing around with the pattern matching it's very useful to have metadata to be able to directly see names instead of only jersey numbers. Let's spend some time on this one soon

**Comment by koenvo** [comment]
@bdagnino does it make sense for your usecase to attach a metadata attribute to the dataset containing the metadata?

**Comment by bdagnino** [comment]
@koenvo yes. Let me know if you want any help with the implementation or need any extra feedback.

**Comment by koenvo** [comment]
Would be good to discuss the models in more detail. 

It should include at least:

```python

class Metadata:
   home_team: Team  # this might break for EPTS without teams..
   away_team: Team

class Team:
    team_id: str   # provider ID. This can also be 'home' / 'away' in case provider doesn't include ids
    name: str
    players: List[Player]

class Player:
    player_id: str  # provider ID. must be unique over all players. In case a provider does have non-unique values it must be prefixed with 'home_' or 'away_'. This is the case for TRACAB/Metrica CSV which only has jersey numbers
    jersey_number: int
    position: Position
    name: str
    first_name: str
    last_name: str

class Position:
   position_id: str
   name: str
```

**Comment by bdagnino** [comment]
Nice! Solid base! Additions I think are important:

1. Pitch for the dimensions of the field, it would be the same Pitch model already available the models/common.py
2. frame_rate
3. score
4. Periods, same as in models/common.py

In the future we could consider adding Subtitutions, but not necesary for now I believe. 

So the model would be:

```python
class Metadata:
   home_team: Team  # this might break for EPTS without teams..
   away_team: Team
   pitch: Pitch
   score: List # first home, second away [0,0]
   periods: List[Period]
   frame_rate: float


class Team:
    team_id: str   # provider ID. This can also be 'home' / 'away' in case provider doesn't include ids
    name: str
    players: List[Player]

class Player:
    player_id: str  # provider ID. must be unique over all players. In case a provider does have non-unique values it must be prefixed with 'home_' or 'away_'. This is the case for TRACAB/Metrica CSV which only has jersey numbers
    jersey_number: int
    position: Position
    name: str
    first_name: str
    last_name: str

class Position:
   position_id: str
   name: str

```

What do you think?

**Comment by koenvo** [comment]
I rather don't have copies of periods/pitch/frame_rate. So I would then move all attributes other than `records` (which are metadata actually) from Dataset to Metadata. For compatibility we can add some deprecated properties on Dataset that return values from Metadata.

That way metadata and data are nicely separated.

**Comment by bdagnino** [comment]
Sounds good! I think it makes sense to have the info only on metadata, and only data in the dataset.

**Comment by koenvo** [comment]
I would keep a reference from the dataset to the metadata as the container (Dataset) makes it easy to pass it around. And processing the records often require the Metadata too.

```python

class Dataset:
   records: List[Frame/Event]
   metadata: Metadata

  @property
  def periods(self):
    return self.metadata.periods

class Metadata:
   periods: List[Period]
   ..... etc ....
```

**Comment by davidlamb** [comment]
I'm interested in cotributing to this project. Is this issue available to work on, or needs that I could get started on?

**Comment by koenvo** [comment]
Hi @davidlamb it would be great when we have some more examples, that we can also use in the documentation. We can also have a chat at twitter (@ mr_le_fox) to discuss which issue is good to start with.

**Comment by koenvo** [comment]
Related to the metadata issue: fixed in https://github.com/PySport/kloppy/pull/34
