### ISSUE TITLE
README Quickstart Files

### ISSUE THREAD

**Issue by fsartoris** [PySport/kloppy#30]
Hi, i am very interested in this kind of projects related to Data & Sports. I am following the README instructions and into the Quickstart section I cannot find the files for each tracking system defined. I understand that each one has published or shared some data files to start using/experimenting this tool but I cannot found into the repo. These files are in another repo? Where is the location? 

I.E. below CSV files are not present in the repo. Same issue with other examples.
# metrica data
dataset = load_metrica_tracking_data('home_file.csv', 'away_file.csv')

I can fork the repo and add this information in the README if i know where are this files.
Congratulations for your work and i am ready to collaborate in the future. 

Thanks.

**Comment by koenvo** [comment]
Thanks for your feedback. We are working on getting the documentation at a higher level. The example you refer to is when you have those files from a provider yourself.

When you want to start and use public data I advise you to use the `datasets` api. This will make sure the files are fetched and get you going right away. https://github.com/pySport/kloppy#public-datasets--very-quick-start

Hope this helps!

**Comment by koenvo** [comment]
I'll close this one for now. Please reopen if you think this issue is not resolved.
