### ISSUE TITLE
Drop Python 3.7 support

### ISSUE THREAD

**Issue by koenvo** [PySport/kloppy#314]
Currently we run tests for Python 3.7 and have make sure everything works. 

I propose to drop support for 3.7 in the next release and remove the tests. The current version might or might not work on 3.7 but we won't fix 3.7 related issues.

Some issues:
- `macos-latest` on Github actions doesn't support 3.7 (requires this fix: https://github.com/actions/runner-images/issues/9770 )

<img width="836" alt="image" src="https://github.com/PySport/kloppy/assets/3765024/8b238982-1803-481b-b987-8faee6705bca">

Source: https://devguide.python.org/versions/ (May 22th 2024)

**Comment by probberechts** [comment]
Python 3.7 has reached its end of life, so dropping support for it seems reasonable. According to pypistats most users are on Python >=3.9.

**Comment by JanVanHaaren** [comment]
I'm also fine with dropping support for Python 3.7.

https://peps.python.org/pep-0537/#schedule-last-security-only-release
