### ISSUE TITLE
Add a provider type to dataset.metadata

### ISSUE THREAD

**Issue by bdagnino** [PySport/kloppy#36]
I think a good addition in the future would be to add a provider type to the metadata. That way you would know from which provider the data came, to check if you need to for example:

- handle it differently when for example transforming coordinates, 
- syncing tracking and event data of different providers
- doing or not a certain step on your analysis if data comes from one provider or the other one. 

We could add it in the `kloppy\domain\common.py`, something like:

```python

class Provider(Enum):
    METRICA= "metrica"
    TRACAB = "tracab"
    OPTA= "opta"
    STATSBOMB = "statsbomb"

    def __str__(self):
        return self.value

@dataclass
class Metadata:
    teams: List[Team]
    periods: List[Period]
    pitch_dimensions: PitchDimensions
    score: Score
    frame_rate: float
    orientation: Orientation
    flags: DatasetFlag
    provider: Provider
```

I'll eventually need it for a project I'm working on and I could do it then, but could also be a good first issue for someone else that want's to contribute.

**Comment by koenvo** [comment]
Indeed a good first issue!

**Comment by FCrSTATS** [comment]
Is the provider of the event data stored already? if not, is there a natural place for this to be stored?

**Comment by bdagnino** [comment]
@FCrSTATS each Dataset has a Metadata field. So for example if you have tracking from Tracab and events from Opta, you would have two datasets, one for tracking (dataset.metadata.provider = Tracab) and one for events (dataset.metadata.provider = Opta)

**Comment by FCrSTATS** [comment]
thanks Bruno, where is dataset.metadata.provider assigned?

**Comment by bdagnino** [comment]
It isn't yet, that's what this issue is about 😺

**Comment by FCrSTATS** [comment]
"is" == "should" :) 

seems sensible to add to kloppy\domain\common.py as you suggested but is there a natural point at which it would be used

**Comment by bdagnino** [comment]
it might be the lack of caffeine, but I'm not sure I understand what you mean.

**Comment by koenvo** [comment]
Fixed in https://github.com/PySport/kloppy/pull/38
