### ISSUE TITLE
More non-generic events

### ISSUE THREAD

**Issue by rjtavares** [PySport/kloppy#43]
More common event types (like Tackles and Interceptions) should have their own types within kloppy. Should an issue be created for each type in order to discuss how to convert different providers to a common framework?

**Comment by bdagnino** [comment]
@rjtavares I discussed this issue with @koenvo and we will start working on adding new "kloppy standard" events. The trigger for this was to allow for a better definition of sequences (consecutive actions on which a team is in control of the ball).

Currently I'm thinking of adding:

- GOAL KICK, KICK OFF, FREE KICK, THROW IN, PENALTY, CORNER KICK
- BALL OUT
- RECOVERY
- FOUL

On some providers, some of these are events already. For example, in Metrica event data there is a ball out event, same in opta. However, on others like statsbomb, _out_ is a sub-type/qualifier for a pass or shot event. In those cases, my thinking is to leave the pass or event as it is now, but add a synthetic event at the time the ball went out of type BALL OUT. 

@koenvo what do you think? About this approach and about the list of events?

@rjtavares if you want to include other events as originally mentioned in the ticket this might be a good time to consider that as well. What do you think / would like to be considered?

**Comment by rjtavares** [comment]
What's the difference between Recovery and Interception? Is it the same concept?

The only somewhat standard events missing from that list are: Tackles, Take-ons/Dribbles, Aerial Duels.

**Comment by bdagnino** [comment]
@rjtavares a _recovery_ could be an _interception_, but could also be other things as well, for example it could be a ball stolen from the feet of other player. The idea for this _recovery_ is to be able to define the start of sequences that did not start from a pass, for example a recovery followed by a carry. 

I'll have a look at the other events you mentioned as well and see which ones can be easily generalized between providers.

**Comment by bdagnino** [comment]
I'm compiling some information about different event types [here](https://docs.google.com/spreadsheets/d/1zomK8r8CKqxHSK8BY9A25BCWie-J-NU4tT07hBC5UB0/edit?usp=sharing).

**Comment by bdagnino** [comment]
@koenvo as discussed, I'll work on adding:

_Related to start and end of sequences_
RECOVERY
BALL_OUT
FOUL_COMMITTED

_Events that involve a pass_
GOAL_KICK
FREE_KICK
THROW_IN
CORNER_KICK
PENALTY
KICK_OFF

_Implementation_
Each one of the above will be a new EventType. For the ones that represent a pass, I suggest giving an EventType as input to the creation of the instance, with a default to EventType.PASS.

I'll start working on this implementation tomorrow for all providers.

**Comment by bdagnino** [comment]
@koenvo I implemented the approach we discussed on PR #70. However I ran into a conflict with this approach regarding free kicks. We discussed following the approach of whenever there was a set piece, replace the event PASS or SHOT by the SET PIECE TYPE. This works well for almost all event types but for FREE KICKS. 

A FREE KICK can be followed by a PASS, or a SHOT. If we replace PASS and SHOT by FREE KICK indistinctively we will loose the info about what type of action that FREE KICK represented. 

We can only change PASS for FREE KICK and leave SHOT as it is, but the when filtering for FREE KICKS you wouldn't get the FREE KICKS in which they player shoot straight to the goal. 

Can you think of a way to address this issue?

**Comment by bdagnino** [comment]
@koenvo I gave this some thought but are not sure there is a way to solve this in the current approach we are taking. Even if we solve this particular conflict we would be very limited in the amount of subtypes or qualifiers we can encode for. For example, crosses, or cutbacks, or type of challenges, or whether a shot was a header or a shot with the foo etc. 

I suggest we consider another approach. We could define a subtypes or qualifiers attribute to the Event class, which is a list of different possible Subtypes or Qualifiers which could be an enum. For example:

```python
# Subtypes could also be called Qualifiers
class Subtypes(Enum):
    GOAL_KICK = 1
    THROW_IN = 2
    FREE_KICK = 3

@dataclass
class Event(DataRecord, ABC):
    # all current attributes
    subtypes: List[Subtypes] = field(default_factory=list)
``` 

And then when doing `dataset.to_pandas()` each subtype could be a column with the name of the Subtype and a 1 if that event has that subtype and a 0 if not. 

This way we have a flexible way to encode diferente event subtypes or qualifiers from the get go and even could allow for custom subtypes/qualifiers by the user. 

What do you think?

**Comment by koenvo** [comment]
On the Event side I tend to qualifier (or attributes / properties). And make sure the Event.qualifiers can hold more types of info like foot. Then we can add a method on the event the easy retrieve the value of a certain type of qualifier.

event.get_qualifier(Foot) == Foot.Left

And I think we should split out all the pandas related code to a separate file to allow expanding the to_pandas part and keep the code clean. Then we can also provide different types of to_pandas implementions to fit everyone’s needs
