### ISSUE TITLE
Adding a data type type to the datasets

### ISSUE THREAD

**Issue by bdagnino** [PySport/kloppy#45]
@koenvo I'm working with games in which I have a tracking dataset and an event dataset, and I'd like to have share methods, like for example `get_team_dataframe`  which should do different things depending on of the dataset is a tracking dataset or an event one. 

I'd propose we add a type DataType and a data_type attribute to the Datasets:

```python
class DataType(Enum):
    TRACKING = "tracking"
    EVENT = "event"

@dataclass
class Dataset(ABC):
    records: List[DataRecord]
    metadata: Metadata
    data_type: DataType
```

If you agree with this, I can implement it.

**Comment by bdagnino** [comment]
Another option could be to include it inside `metadata`. I think since this is descriptive of the dataset it belongs to the dataset though, but don't have a high conviction on that.

**Comment by bdagnino** [comment]
Closing issue as I realized I don't need this actually for now at least. Happy to do it still if relevant, but don't want to leave the issue open if not needed.

**Comment by koenvo** [comment]
I reopen this because it’s a good first issue and like to have more of those.

Implementation should be similar to https://github.com/PySport/kloppy/blob/master/kloppy/domain/models/event.py#L82

**Comment by bdagnino** [comment]
Perfect! I'll remove myself from this issue then. But happy to help whomever ends up implementing it if needed.

**Comment by eujern** [comment]
May I take a stab at this one?

**Comment by bdagnino** [comment]
@eujern yes! Let me know if you need any help or guidance.

**Comment by eujern** [comment]
Actually, have a question while working on this.  `Dataset` is an abstract class, and we have `EventDataset` and `TrackingDataset` implement it.  Why is it still necessary to have an explicit `data_type` field?  For the `get_team_dataframe` example above, wouldn't you just add an abstract method to `Dataset`, and then implement them separately in `EventDataset` and `TrackingDataset` for event and tracking data respectively?

**Comment by eujern** [comment]
Or if the method should not be a part of `Dataset`, couldn't you just an `isinstance(dataset, EventDataset)` check in the method?

**Comment by koenvo** [comment]
> Actually, have a question while working on this. `Dataset` is an abstract class, and we have `EventDataset` and `TrackingDataset` implement it. Why is it still necessary to have an explicit `data_type` field? For the `get_team_dataframe` example above, wouldn't you just add an abstract method to `Dataset`, and then implement them separately in `EventDataset` and `TrackingDataset` for event and tracking data respectively?

I prefer this one. In a previous comment I referred to the event implementation which is similar.

**Comment by eujern** [comment]
> > Actually, have a question while working on this. `Dataset` is an abstract class, and we have `EventDataset` and `TrackingDataset` implement it. Why is it still necessary to have an explicit `data_type` field? For the `get_team_dataframe` example above, wouldn't you just add an abstract method to `Dataset`, and then implement them separately in `EventDataset` and `TrackingDataset` for event and tracking data respectively?
> 
> I prefer this one. In a previous comment I referred to the event implementation which is similar.

@koenvo to clarify, you prefer adding a `data_type` field to `Dataset`, the same way `event_type` is implemented in `Event`?

**Comment by koenvo** [comment]
Yes indeed

**Comment by bdagnino** [comment]
1. The `get_team_dataframe` I referred to was on another repo that is using kloppy, not on kloppy itself. 
2. My 2cts on this topic: while using `isinstance` would work, in my view having a datas_type is cleaner than having to check the instance. It's visible when you look at the object / more straightforward to use.

**Comment by eujern** [comment]
Thanks for clarifying!

**Comment by koenvo** [comment]
Thanks @eujern !
