### ISSUE TITLE
Read EPTS data provider from metadata.xml file

### ISSUE THREAD

**Issue by bdagnino** [PySport/kloppy#46]
@koenvo now you can set the provider of the EPTS data from `load_metadata`, however you can't do it from the load helper method `load_epts_tracking_data`. Wold be nice to have it there as well so you can use this helper without having to set it after the dataset is created. 

I can implement this if you agree.

**Comment by koenvo** [comment]
Can we detect it from the file itself? Even an ugly way (like checking existence of certain values in the xml)

 When a user has to specify it I’m not sure I see the goal of it.

**Comment by bdagnino** [comment]
Yes, you are right. Moreover, there is actually an attribute  in the file for provider `<ProviderName>Example</ProviderName>` so we can use that to check for known providers. Do you want to leave this one also as a good first issue? I'm in no urgency for this yet.

**Comment by TK5-Tim** [comment]
@bdagnino So basically `load_epts_tracking_data` should work similar to `load_meta_data`?

**Comment by bdagnino** [comment]
@TK5-Tim not exactly. That's what I originally proposed, but @koenvo suggested a better approach. His proposal is to read the provider from the ETPS metadata file itself when loading the metadata. For that the following background is important:

1. If you look [here](https://github.com/PySport/kloppy/blob/1c9a62948a43313130be52bc5874f573d20b5d8b/kloppy/domain/models/common.py#L24) you'll see there are 4 providers, for now the only one that metters for the EPTS sreializer is Metrica, because we are the only ones providing data in the EPTS format (at least that we have access to), but this is relevant for this issue. 

2. Then you'll see that [load_metadata](https://github.com/PySport/kloppy/blob/1c9a62948a43313130be52bc5874f573d20b5d8b/kloppy/infra/serializers/tracking/epts/metadata.py#L153) takes 2 arguments, the `metadata_file` and the provider if known. In this case the provider won't be known beforehand, because it's declared in the metadata file. 

3. The metadata file, has provider name attribute. In the example file that's on the tests folder of Kloppy it says `<ProviderName>Example</ProviderName>`, in files from Metrica is says `<ProviderName>Metrica Sports</ProviderName>`.

So the implementation would be to inside `load_metadata` read the `ProviderName` attribute and if it matches `Metrica Sports`, then set the provider to Provider.METRICA, and otherwise leave it as None. Later on when we get more EPTS files from other providers, we'll need to add there other cases as well. 

This should also be tested on a test, for which you can either create a new metadata.xml file where `ProviderName` is `Metrica Sports` or change the one already there. 

Hope it's clear but let me know if you have any questions!

**Comment by TK5-Tim** [comment]
@bdagnino Thank you very much, now I get the task. Do you prefer still having the argument but having it changed by the file if found in the file or should I take out the argument? 

If the provider is not in the XML it would helpful to be able to put it down manually. Otherwise I do not even know if there is any reason not to have the providers name in the XML.

**Comment by bdagnino** [comment]
@TK5-Tim great!

Yes, we should leave the option to provide is an an input as well to `load_matadata`. If there is one provided but a different one in the metadata.xml we should probably raise a warning.

**Comment by koenvo** [comment]
Fixed in https://github.com/PySport/kloppy/pull/52
