### ISSUE TITLE
Add length and width property to PitchDimensions

### ISSUE THREAD

**Issue by bdagnino** [PySport/kloppy#47]
Currently there is a PitchDiementions object as attribute in the Metadata of a Dataset. The PitchDimension class has attributes `[x,y]_dim`  and`[x,y]_per_meter` but there is no property to directly get the `length` or `width` of the field. 

Would be good to have something like the below implemented so you an get directly get the dimensions of the field in meter without having to do extra calculations. 

```python
@dataclass
class PitchDimensions:
    x_dim: Dimension
    y_dim: Dimension
    x_per_meter: float = None
    y_per_meter: float = None

    @property
    def length(self) -> float:
        return self.x_dim.max / self.x_per_meter

    @property
    def width(self) -> float:
        return self.y_dim.max / self.y_per_meter
```

This would work for the EPTS dataset/metadata, not sure it requires catching exceptions for other providers / formats. Those will need to be taken into account as well.

**Comment by BenjaminLarrousse** [comment]
Is there a place where I can find data spec for providers? 
I imagine _x_per_meter_ and _y_per_meter_ are not always provided. If not, we can always catch the exception and set _length_ and _width_ to None

**Comment by koenvo** [comment]
I think you should not take the data provided into account. Your suggestion to try to return it and when it fails return None sounds very good.
Also take into account that you need `Dimension.mix` in case the min value is other than 0

**Comment by BenjaminLarrousse** [comment]
Sure, should be `self.x_dim.max - self.x_dim.min`

Is there a test file I should put a test for these properties? (I'm still getting used to the package)

**Comment by koenvo** [comment]
Create a new test file please which will contain tests for metadata. test_metadata.py should work

**Comment by koenvo** [comment]
Thank you @BenjaminLarrousse !

**Comment by BenjaminLarrousse** [comment]
> Thank you @BenjaminLarrousse !

You're welcome. I'll get on another issue soon. This one was to for me to start understanding the code, I can do more complicated things now.
