### ISSUE TITLE
Setup code formatting tool

### ISSUE THREAD

**Issue by koenvo** [PySport/kloppy#5]
kloppy doesn't have any code formatting tool in place. To make sure the code will be maintainable in the long term a code formatter is needed.

Black ( https://github.com/psf/black ) might be a good option.

**Comment by dmallory42** [comment]
Hi, are you accepting contributions on this?

**Comment by koenvo** [comment]
Yes!

**Comment by dmallory42** [comment]
I've created a pull request for this issue: #23

**Comment by koenvo** [comment]
Thanks @dmallory42
