### ISSUE TITLE
to_pandas fails for Opta data when trying to read player_id

### ISSUE THREAD

**Issue by bdagnino** [PySport/kloppy#57]
Some event types, like `formation change` do not have a `player_id` attribute. `to_pandas` should check that and return `None` for `player_id` if not is available in the event. 

![Skrmbillede_2020-09-01_kl _12 29 01](https://user-images.githubusercontent.com/5121185/91854785-a17fff80-ec3a-11ea-90b8-9d2d4b698606.png)

**Comment by koenvo** [comment]
Fixed in https://github.com/PySport/kloppy/pull/58
