### ISSUE TITLE
Remove 'deleted events' from OPTA f24 data 

### ISSUE THREAD

**Issue by FCrSTATS** [PySport/kloppy#60]
I would propose that as default load_opta_event_data() would remove 'deleted events' from the dataset with the option to override. 

Deleted events would be looked at in extremely rare circumstances but could cause some issues with analysis

**Comment by koenvo** [comment]
Can you provide an example of deleted events?

**Comment by koenvo** [comment]
@FCrSTATS do you have a file with this deleted events in it?

**Comment by rishicarter** [comment]
As per the documentation of Opta's F24 match feed data, deleted events are associated with `type_id='43'` and a `qualifier_id='144'`. As per my understanding, once an event is deleted, Opta does remove the associated event's data but the value of the _event_id_ attribute remains in the feed with `type id='43'`. An example of a deleted event:

![image](https://user-images.githubusercontent.com/26142477/231436007-0f719d86-a83f-440d-8452-ca40d846e6fc.png)

Source: [Link](https://github.com/jokecamp/FootballData/blob/master/random_docs/Opta-f24_appendices.docx)

I also checked the dict _**event_type_names**_ in the _deserializer.py_ file and found id - '43' to be associated with 'deleted events'. I believe a possible fix can be to skip the deleted events completely. If this sounds reasonable,  I would be happy to work on implementing this fix.
