### ISSUE TITLE
add a function to calculate the distance to a position within the Point class

### ISSUE THREAD

**Issue by FCrSTATS** [PySport/kloppy#62]
there is a need to calculate distances between a player and a position (other players, the ball, an area, etc) 

I think it would be beneficial to have a function within the Point class that returns a distance 

something like 

def distance_to(self, another_point):
       distance = ....some calc.... 
       return distance

what are peoples thoughts of this function being located within the Point class?

**Comment by koenvo** [comment]
Yes! Please create a PR for this

**Comment by koenvo** [comment]
Thanks @FCrSTATS !

Fixed in https://github.com/PySport/kloppy/pull/63
