### ISSUE TITLE
Transforming Tracking Data not working

### ISSUE THREAD

**Issue by schmidtfx** [PySport/kloppy#65]
Hi,
I have kloppy==1.2.1 and I'm running into an issue transforming metrica tracking data.

`
from kloppy import datasets, helpers
dataset = datasets.load("metrica_tracking", options={})
dataset = dataset.transform(dataset, to_pitch_dimensions=[[0, 105], [-34, 34]])
`

This gives me the following error message:
`
AttributeError: 'TrackingDataset' object has no attribute 'get_orientation_factor'
`

Am I doing something wrong? Any suggestions?

**Comment by koenvo** [comment]
kloppy should raise an exception to make it clear you are passing too many arguments.

```python
from kloppy import datasets

dataset = datasets.load("metrica_tracking", options={}) 
dataset = dataset.transform(to_pitch_dimensions=[[0, 105], [-34, 34]])
```

you should not pass the dataset itself to the transform method.

**Comment by koenvo** [comment]
Closing this for now
