### ISSUE TITLE
'id' being used as 'event_id' instead of 'event_id' in f24 parsing

### ISSUE THREAD

**Issue by FCrSTATS** [PySport/kloppy#69]
When we parse opta f24 data we use 'id' and allocate it to 'event_id' in our event class. But we then seem to discard 'event_id' from the f24. seems there is a need to keep the original event_id as well?

see here [line](https://github.com/PySport/kloppy/blob/17ccd751c42bcf5656ab6fd50f6423816d10260b/kloppy/infra/serializers/event/opta/serializer.py#L365)

**Comment by koenvo** [comment]
You should be able to fetch that from the `event.raw_event` like this: `event.raw_event.attrib['event_id']`

For reference purposes: how can I get the qualifiers from an Opta feed?
`qualifiers = {q.attrib['qualifier_id']: q.attrib.get('value') for q in event.raw_event.findall('Q')}`
