### ISSUE TITLE
Implement BodyPart qualifier for Statsbomb

### ISSUE THREAD

**Issue by koenvo** [PySport/kloppy#82]

**Comment by BenjaminLarrousse** [comment]
BodyPart qualifier exists for Goalkeeper, pass and shot.

We could add it inside _parse_pass() for pass and _parse_shot() for shots (inside the Statsbomb's serializer). A bit like "outcome" is created.

The goalkeeper part is not taken care of, I think ?

**Comment by koenvo** [comment]
@BenjaminLarrousse the goalkeeper is not implemented at all indeed. I would prefer to have BodyPart implemented for each provider first, and then add the GoalKeeper event(s). 

Would you like to implement this for Statsbomb?

**Comment by BenjaminLarrousse** [comment]
Yes I do!

The way I see things:

- in models/event.py, add all possible body part values in the BodyPart class (I can add values for pass, shot, goalkeeper even if we don't use goalkeeper values for now)
- in the Statsbomb's serializer, in _parse_pass and _parse_shot, set a _body_part_ value based on the id inside the source file. For example, `body_part = BodyPart.LEFT_FOOT` if  `pass_dict["body_part"]["id"] = 38`. add a _body_part_ key in the returned dict of the function.
At the top of the file, I can set the value as you did for other events (e.g. SB_BODYPART_LEFT_FOOT = 38)
- Add a test to be sure it works the way it should

Do you see things I should be careful about when implementing this?

**Comment by koenvo** [comment]
That sounds like a great plan @BenjaminLarrousse, and I think you mentioned all important parts 👍

**Comment by BenjaminLarrousse** [comment]
@koenvo  I created a pull request. I think it's good.

Look at it when you have the time and let me know. Thanks

**Comment by koenvo** [comment]
Fixed in https://github.com/PySport/kloppy/pull/86
